[package]
name = "sm-encoders"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
keystone-engine = { version = "0.1.0", features = ["use-system-lib"] }
rand = "0.9.1"
thiserror = "2.0.12"
